# This is a basic workflow to help you get started with Actions

name: peviitor.ro

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Apache JMeter
         # You may pin to the exact commit or the version.
         # uses: rbhadti94/apache-jmeter-action@8441308b8d05c3acc6e61f11149b4e1d3b3ccd98
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
         # The path to the JMX test file
         testFilePath: ./
         outputReportsFolder:  reports/
         plugins: jpgc-dummy
          
          
